### ISSUE TITLE
Advanced walkthrough documentation [website]

### ISSUE THREAD

**Issue by amerikan** [abella-prover/abella#100]
Not sure if this is the best channel to mention this, but....

I was going through the advanced walk through on the website, http://abella-prover.org/advanced-walkthrough.html There's a theorem referred as `member_uniq`.

At the very bottom there's a link to:  http://abella-prover.org/examples/lambda-calculus/type-uniq/type-uniq.html On this page it is called as `ctx_uniq`. 

It appears they're both the same exact thing. It threw me off for a bit. It would be good to just use one or the other for consistency.

**Comment by chaudhuri** [comment]
Thanks. This should [now be fixed](https://github.com/abella-prover/abella-prover.org/commit/c9cbb26408066517cf3398946d99367bfa4a1f96).
