### ISSUE TITLE
"search" does not ensure that all logical variables are instantiated with ground terms

### ISSUE THREAD

**Issue by yvting** [abella-prover/abella#105]
Consider the following examples:
```
Kind i type.

Theorem foo : exists (x:i), x = x.
search.

Theorem bar : exists (x y:i), x = y.
search.
```

For 'foo', search will generate an logical variable for 'x' and consider the equality to be provable.

For 'bar', search will generate logical variables for 'x' and 'y' and unify 'x' with 'y'. Again, the goal is proved  without checking that 'x' and 'y' are instantiated to ground terms.

**Comment by chaudhuri** [comment]
As far as I can tell, this is not a bug since you can use nominal constants
in both cases. If we ever get around to differentiating between nominal and
non-nominal types, this may be an important thing to watch out for.

**Comment by yvting** [comment]
Close this issue since it is not a real problem for now.
