### ISSUE TITLE
Suspend declarations and Imports

### ISSUE THREAD

**Issue by ThatDaleMiller** [abella-prover/abella#159]
There is something odd with suspends and imports.  I suspect that suspensions have not been incorporated into the thc files.  In any case:  

Let nat.thm be the following file.
```
Kind nat type.
Type z nat.
Type s nat -> nat.
Define nat : nat -> prop by nat z ; nat (s N) := nat N.
```
If I run Abella 2.1.0-dev on the following script, I get an infinite loop with the ``compute H3`` command.
```
Import "nats".

Define plus : nat -> nat -> nat -> prop by
	plus z N N := nat N
;	plus (s M) N (s K) := plus M N K.

Theorem augend_nat : forall A B C, plus A B C -> nat B -> nat C -> nat A.
induction on 1. intros. case H1.
  search.
  compute H3.
  apply IH to H4 H2 H5. search.
```
This seems odd since the default suspension is to suspect (nat X) when X is an eigenvariable.
If I insert ``Suspend nat X := X`` into nat.thm, the same looping happens.  If I insert it into the testing script above, the proof completes okay.  If I insert it both places, it works also okay.

I'll do more development work without using the Import command for now.

**Comment by chaudhuri** [comment]
Should be fixed now, hopefully.
