### ISSUE TITLE
Command line argument for setting options

### ISSUE THREAD

**Issue by lambdacalculator** [abella-prover/abella#42]
As a feature request, I propose adding an additional command-line switch to the Abella executable, with help string

    -s <option> <value>   Set option at startup

that, as the help string says, performs the equivalent of command `Set <option> <value>` at start-up. This would be useful in situations like

    % abella -s subgoals 0  -s witnesses on  -o theorems.out  theorems.thm

**Comment by chaudhuri** [comment]
All right. Sounds reasonable. It's on the stack.

**Comment by lambdacalculator** [comment]
I liked "-s" for "Set," as in Abella's top-level command, rather than "-f" for "flag," which seems more appropriate for things that are turned on or off -- unless you were planning to change the manual so that "Options" become "Flags". In any case, I'm glad to see the functionality added, thanks!
