### ISSUE TITLE
Subgoal numbering can have duplicates

### ISSUE THREAD

**Issue by chaudhuri** [abella-prover/abella#49]
I would recommend additionally taking a careful look at the code that generates subgoal numbers. The other day, I came across a small bug in the middle of a big proof that involved two successive subgoals being given the same number. I didn't make a ticket for it because I didn't have the time to isolate the problem and extract a small portion of my large development that illustrated it at the time, and now I can't find it again, although I'm sure it was there. This was the only time I've seen it happen, however, so it seems quite rare. I'm passing along this information here just as a head's up, since, if you end up implementing my suggested features, then you will at least be looking at this code, and if you pay a little extra attention to the invariants there, you might spot the problem.

(From #44 by @lambdacalculator)

**Comment by chaudhuri** [comment]
Haven't located the source of the bug in a quick look through the subgoal numbering code. Possibly has something to do with `undo`/`#back`.

**Comment by chaudhuri** [comment]
This is almost certainly caused by the same bug that afflicted #41.

**Comment by lambdacalculator** [comment]
Thanks. I'll use the corrected version and reopen the ticket if I ever see
it happen again.

**Comment by chaudhuri** [comment]
Closing this as unreproducible. Please reopen if you need to.
