### ISSUE TITLE
Inconsistency when backchaining on non-variable flexible head

### ISSUE THREAD

**Issue by chaudhuri** [abella-prover/abella#50]
This passes Abella.

    Kind i type.
    Type p i -> o.
    
    Theorem incons_1 :
      forall F U, {[pi x:i\ F x] |- p U} -> exists X, F X = p U.
    intros. case H1. witness x. search.
    
    Theorem incons_2 :
      nabla u, {[pi x:i\ (p x => p x) => p u] |- p u}.
    search.
    
    Theorem incons : false.
    apply incons_2 with u = n1.
    apply incons_1 to H1.

Ping @yvting.

**Comment by chaudhuri** [comment]
In fact, the same bug also exists for implications.

    Theorem incons_3 :
      forall F U, {[(p U => p U) => F] |- p U} -> F = p U.
    intros. case H1. search.
    
    Theorem incons_4 :
      forall U, {[(p U => p U) => (p U => p U) => p U] |- p U}.
    intros. search.
    
    Theorem incons' : false.
    assert exists (F:o) (U:i), true. case H1.
    apply incons_4 with U = U.
    apply incons_3 to H2.

**Comment by chaudhuri** [comment]
Experimenting a bit more, 4acf130 is not a fix because it is too destructive. It prevents all reasoning on, e.g., `{L, [F => G] |- p X}`, when really we should at least be able to get the pair `{L |- F}` and `{L, [G] |- p}` from that. Back to the drawing board.

**Comment by yvting** [comment]
I think you can do a full backchaining when the head predicate of the focused formula is known. If the head is flexible then you do a partial backchaining that stops when the flexible head is reached.

**Comment by chaudhuri** [comment]
Right, that's what I'm implementing now.
