### ISSUE TITLE
Make prune_arg automatic

### ISSUE THREAD

**Issue by lambdacalculator** [abella-prover/abella#52]
Because `member` is a built-in predicate, `prune_arg` should be applied automatically to eliminate impossible cases in `member` hypotheses. Thus, for example, given

```
H4: member (of n1 A) (of n1 B :: G)
H5: member (of n1 A) (of n2 B :: G)
```

`case H4` should unify A and B and produce no additional subgoals, and `case H5` should succeed immediately.

Of course, this would eliminate the need for `prune_arg` and break a lot of developments (including all of my own), but it is arguably the right thing from a system perspective.

**Comment by lambdacalculator** [comment]
As an additional comment, you could also consider not even generating these `member` hypotheses if they can be eliminated by a sequence of `case` invocations without introducing extra subgoals. The only ones that would ever appear would be the ones in "normal form" `member (E x) (G x)`, where `E x` can be an explicit predicate, or `member (E x) (E' x :: G x)`, where `E` and `E'` can unify in multiple ways. In the latter case, you are still giving the users the choice of when to do the `case` on `member`, so that they can prepare additional hypotheses useful in all of the subgoals first, if they wish.

**Comment by chaudhuri** [comment]
I've considered doing this several times. It's even easy to implement. (See #21, #35) However, this would mean treating `member` specially and I am not sure it's such a great idea. Also backwards incompatible proof language changes won't happen before 2.1.

**Comment by chaudhuri** [comment]
This is now unlikely to happen as proposed as we have decided to move towards adding reasoning modules to Abella. Also, once the `sch_poly` branch is merged, there will be minor changes in the sort of polymorphism we support.

We may revisit this in a future 3.0 change as part of the context-related changes planned.
