### ISSUE TITLE
Accidentally capturing bound variables by the 'exists' tactic

### ISSUE THREAD

**Issue by yvting** [abella-prover/abella#54]
This bug is illustrated by the following example:

    Kind i type.

    Type app   i -> i -> i.
    Type abs   (i -> i) -> i.
    Type p  i -> prop.

    Theorem foo : exists M, forall (x:i), p (M x).
    exists (y\ abs x\ app x y).

Applying the last tactic results in the goal:

     forall x, p (abs (x\app x x))

Where an occurrence of `x` bound by forall is accidentally captured by the binder `x` in the instance for `exists`.

**Comment by chaudhuri** [comment]
This is actually a printing bug, which you can see if you follow up with:

    intros. rename x to z.

This will produce the goal:

    Variables: z
    ============================
     p (abs (x\app x z))

which is not at all objectionable.
