### ISSUE TITLE
Various problems with the test suite

### ISSUE THREAD

**Issue by robblanco** [abella-prover/abella#57]
There is (as far as I can tell) no easy way to build and run the test suite. I am experimenting with minimal changes to get this working in a branch of my local fork (https://github.com/robblanco/abella/tree/tests).

Notably, many tests seem to have run out of sync with the module APIs they test and fail to compile. Among those that work I have noticed some regressions. I think getting all these back up and running is important. What do you think?

**Comment by chaudhuri** [comment]
I looked into it around the 2.0.x change but it was a lot of work to port the tests over. Do you have a specific reason for wanting these tests?

**Comment by robblanco** [comment]
Part of me wants them out of principle, because them make Abella better (and the sooner, the less painful). Another part is that I write tests to go with my experiments and it makes no sense to roll my own when there is a test infrastructure in place, waiting to be used.

I have opened a pull request #58 with my tentative changes. As it stands, execution reveals two regressions. I can open issues for these as needed.

**Comment by chaudhuri** [comment]
Interesting. Yes, please open issues for the regressions. I'll review your PR now.

**Comment by chaudhuri** [comment]
Thanks. For reference, Rob just created #59 and #60.

**Comment by chaudhuri** [comment]
All existing tests now pass. Some obsolete tactics tests had to be commented out.

Note that the test suite has basically negligible coverage.
