### ISSUE TITLE
Regression: Normalize should rename nested binders (2)

### ISSUE THREAD

**Issue by robblanco** [abella-prover/abella#59]
From `test/test_metaterm.ml`:

    Failure: Abella:4:Metaterm:33:Normalize should rename nested binders (2)
    
    OUnit: expected: forall A2, A = A1 -> (forall A1, A1 = A1) but got: forall A2, A = A1 -> (forall A3, A3 = A3)

**Comment by chaudhuri** [comment]
This does not seem to be a bug. Normalization was rewritten sometime after 2.0.x and does alpha-variance differently. The test needs to be updated.
