### ISSUE TITLE
Term interface method for `observe (hnorm t)`

### ISSUE THREAD

**Issue by robblanco** [abella-prover/abella#86]
Does it make sense to extend the Term interface with a method that performs a "canonical inspection" of terms, conflating head normalization and `observe`? We have spoken before about how this is a sort of standard, and it makes sense to me if the interface encourages this, and makes it explicit (and more compact).

**Comment by chaudhuri** [comment]
I am not sure `hnorm` needs to be exposed by `Term`, actually, so maybe `observe` can take over the function.

**Comment by robblanco** [comment]
What about `Term.norm`?

**Comment by chaudhuri** [comment]
As far as I can tell, that function isn't used anywhere in Abella.

**Comment by robblanco** [comment]
On this note, I was using `norm` in one of my experiments, but I don't think the code is even composable. In particular, it returns terms with `Var`s unprotected by `Ptr`.

**Comment by chaudhuri** [comment]
I think everything relevant to this issue has already been addressed long ago.
